weights: yolov5n.pt
cfg: ''
data: /cluster/home/it_stu3/Data/4-9homo/armor.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 1000
batch_size: 16
imgsz: 1280
rect: false
resume: false
nosave: false
noval: true
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 16
project: runs/train
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
negative_path:
- /cluster/home/it_stu3/Data/COCO/unlabeled2017/
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/1280
